### PR TITLE
👽️ work around several `mypy` bugs with `numpy>=2.2.0`

### PR DESCRIPTION
**Pull request by jorenham**
blocker: https://github.com/KotlinIsland/basedmypy/pull/842

---

**update**

https://github.com/KotlinIsland/basedmypy/pull/842 has been merged, and there soon will be a `basedmypy==2.8.1` release that includes this fix.

**update 2**

`basedmypy==2.8.1` has been released and is available on mypy, see https://github.com/jorenham/scipy-stubs/pull/293

### CODE REVIEW

**Comment by jorenham** [comment]
unbelievable...

```
Traceback (most recent call last):
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/bin/stubtest", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.13/site-packages/mypy/stubtest.py", line 20[9](https://github.com/jorenham/scipy-stubs/actions/runs/12241514812/job/34146773826?pr=288#step:6:10)8, in main
    return test_stubs(parse_options(sys.argv[1:]))
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.13/site-packages/mypy/stubtest.py", line 1971, in test_stubs
    for error in test_module(module):
                 ~~~~~~~~~~~^^^^^^^^
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.13/site-packages/mypy/stubtest.py", line 247, in test_module
    yield from verify(stub, runtime, [module_name])
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.13/site-packages/mypy/stubtest.py", line 423, in verify_mypyfile
    yield from verify(stub_entry, runtime_entry, object_path + [entry])
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.13/site-packages/mypy/stubtest.py", line 578, in verify_typeinfo
    yield from verify(stub_to_verify, runtime_attr, object_path + [entry])
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.13/site-packages/mypy/stubtest.py", line [10](https://github.com/jorenham/scipy-stubs/actions/runs/12241514812/job/34146773826?pr=288#step:6:11)64, in verify_funcitem
    for message in _verify_signature(stub_sig, runtime_sig, function_name=stub.name):
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.[13](https://github.com/jorenham/scipy-stubs/actions/runs/12241514812/job/34146773826?pr=288#step:6:14)/site-packages/mypy/stubtest.py", line 902, in _verify_signature
    yield from _verify_arg_default_value(stub_arg, runtime_arg)
  File "/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmptyZ58u/lib/python3.13/site-packages/mypy/stubtest.py", line 664, in _verify_arg_default_value
    if runtime_arg.default != inspect.Parameter.empty:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.
```

**Comment by jorenham** [comment]
So `stubtest` crashes with `numpy==2.2.0` (which was released yesterday), and of course, with the most unhelpful stacktrace ever.

I'll submit a basedmypy PR soon with an attempt at a fix. But in the meantime, do you have any ideas on how we could work around this, @KotlinIsland?

**Comment by KotlinIsland** [comment]
so if i understand correctly, stubtest is executing code and it's causing issues. to work around this we could do some hacky patching?
```py
import thing
thing.valuye = patched
from myp import stubtest
stubtest.run
```

**Comment by jorenham** [comment]
> so if i understand correctly, stubtest is executing code and it's causing issues. to work around this we could do some hacky patching?
> 
> ```python
> import thing
> thing.value = patched
> from mypy import stubtest
> stubtest.run
> ```

Yea, but the problem is, I have no idea which one of the 40k lines of code this error originates from 😅

**Comment by KotlinIsland** [comment]
> Yea maybe, but the problem is, I have no idea which one of the 40k lines of code this error originates from

patch `numpy.array.__eq__`?

**Comment by jorenham** [comment]
> > Yea maybe, but the problem is, I have no idea which one of the 40k lines of code this error originates from
> 
> patch `numpy.array.__eq__`?

`numpy.ndarray` is mostly written in `C`, so that's not really an option

```pycon
>>> import numpy as np
>>> np.ndarray.__bool__ = bool
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    np.ndarray.__bool__ = bool
    ^^^^^^^^^^^^^^^^^^^
TypeError: cannot set '__bool__' attribute of immutable type 'numpy.ndarray'
```

**Comment by jorenham** [comment]
> > Yea maybe, but the problem is, I have no idea which one of the 40k lines of code this error originates from
> 
> patch `numpy.array.__eq__`?

For a bit more context, something like this is the source of the error:

```pycon
>>> import numpy as np
>>> np.__version__
'2.2.0'
>>> a = np.array([])
>>> a
array([], dtype=float64)
>>> a == object()  # numpy "vectorizes" the `==` over each element
array([], dtype=bool)
>>> bool(a == object())
Traceback (most recent call last):
  File "<python-input-24>", line 1, in <module>
    bool(a == object())
    ~~~~^^^^^^^^^^^^^^^
ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.

```

**Comment by jorenham** [comment]
basedmypy 2.8.1 solved it, thanks @KotlinIsland!

**Pull request merged**
